// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} tabId
 * @returns {$CancellablePromise<void>}
 */
export function CloseTab(tabId) {
    return $Call.ByID(3508425587, tabId);
}

/**
 * @param {string} tabId
 * @param {string} host
 * @param {string} port
 * @param {string} username
 * @param {string} password
 * @param {string} privateKeyText
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSSH(tabId, host, port, username, password, privateKeyText, passphrase) {
    return $Call.ByID(2974803588, tabId, host, port, username, password, privateKeyText, passphrase);
}

/**
 * @param {string} tabId
 * @param {string} path
 * @param {boolean} isDir
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(tabId, path, isDir) {
    return $Call.ByID(3253734293, tabId, path, isDir);
}

/**
 * DeleteLocalFile removes a file from the local filesystem.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalFile(path) {
    return $Call.ByID(3211582508, path);
}

/**
 * @param {string} tabId
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSSH(tabId) {
    return $Call.ByID(1240619328, tabId);
}

/**
 * @param {string} tabId
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(tabId, remotePath, localPath) {
    return $Call.ByID(3477154054, tabId, remotePath, localPath);
}

/**
 * @param {string} tabId
 * @param {string} remotePath
 * @param {string} safeName
 * @returns {$CancellablePromise<string>}
 */
export function DownloadToTemp(tabId, remotePath, safeName) {
    return $Call.ByID(1152115075, tabId, remotePath, safeName);
}

/**
 * GetConfigDir returns the config directory path (~/.config/ripple-ssh), creating it if needed.
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigDir() {
    return $Call.ByID(2375802737);
}

/**
 * GetFileStats returns the size of a file in bytes.
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function GetFileStats(path) {
    return $Call.ByID(3997025289, path);
}

/**
 * GetOS returns the runtime OS name.
 * @returns {$CancellablePromise<string>}
 */
export function GetOS() {
    return $Call.ByID(2969004750);
}

/**
 * @param {string} tabId
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ListDirectory(tabId, path) {
    return $Call.ByID(3411144651, tabId, path);
}

/**
 * LoadProfiles reads the profiles JSON from the config directory.
 * Returns "[]" if no profiles exist yet.
 * @returns {$CancellablePromise<string>}
 */
export function LoadProfiles() {
    return $Call.ByID(1373793870);
}

/**
 * LoadSettings reads the settings JSON from the config directory.
 * Returns "{}" if no settings exist yet.
 * @returns {$CancellablePromise<string>}
 */
export function LoadSettings() {
    return $Call.ByID(2629865441);
}

/**
 * @param {string} tabId
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(tabId, path) {
    return $Call.ByID(1117168011, tabId, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function NewTab() {
    return $Call.ByID(1452993149);
}

/**
 * OpenFileWithDefaultApp opens a file with the OS default application.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileWithDefaultApp(path) {
    return $Call.ByID(1193656674, path);
}

/**
 * ReadFileAsBase64 reads a file and returns its contents as a base64 string.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileAsBase64(path) {
    return $Call.ByID(2508253217, path);
}

/**
 * @param {string} tabId
 * @param {string} src
 * @param {string} dest
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(tabId, src, dest) {
    return $Call.ByID(447518628, tabId, src, dest);
}

/**
 * @param {string} tabId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(tabId, cols, rows) {
    return $Call.ByID(3309742912, tabId, cols, rows);
}

/**
 * SaveProfiles writes the profiles JSON to the config directory.
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfiles(data) {
    return $Call.ByID(2747840815, data);
}

/**
 * SaveSettings writes the settings JSON to the config directory.
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(data) {
    return $Call.ByID(1632959616, data);
}

/**
 * ShowMessage shows a native dialog with Yes/No buttons and returns the choice.
 * Returns "No" if the dialog is dismissed or times out after 5 minutes.
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function ShowMessage(title, message) {
    return $Call.ByID(368851792, title, message);
}

/**
 * ShowOpenDialog opens a native file open dialog.
 * @returns {$CancellablePromise<string>}
 */
export function ShowOpenDialog() {
    return $Call.ByID(271827769);
}

/**
 * ShowSaveDialog opens a native save file dialog.
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function ShowSaveDialog(defaultName) {
    return $Call.ByID(3437106732, defaultName);
}

/**
 * @param {string} tabId
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(tabId, localPath, remotePath) {
    return $Call.ByID(3829671223, tabId, localPath, remotePath);
}

/**
 * @param {string} tabId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(tabId, data) {
    return $Call.ByID(3608916995, tabId, data);
}
