// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} host
 * @param {string} port
 * @param {string} username
 * @param {string} password
 * @param {string} privateKeyText
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSSH(host, port, username, password, privateKeyText, passphrase) {
    return $Call.ByID(2974803588, host, port, username, password, privateKeyText, passphrase);
}

/**
 * @param {string} path
 * @param {boolean} isDir
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path, isDir) {
    return $Call.ByID(3253734293, path, isDir);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalFile(path) {
    return $Call.ByID(3211582508, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSSH() {
    return $Call.ByID(1240619328);
}

/**
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(remotePath, localPath) {
    return $Call.ByID(3477154054, remotePath, localPath);
}

/**
 * @param {string} remotePath
 * @param {string} safeName
 * @returns {$CancellablePromise<string>}
 */
export function DownloadToTemp(remotePath, safeName) {
    return $Call.ByID(1152115075, remotePath, safeName);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigDir() {
    return $Call.ByID(2375802737);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function GetFileStats(path) {
    return $Call.ByID(3997025289, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOS() {
    return $Call.ByID(2969004750);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ListDirectory(path) {
    return $Call.ByID(3411144651, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LoadProfiles() {
    return $Call.ByID(1373793870);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LoadSettings() {
    return $Call.ByID(2629865441);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(path) {
    return $Call.ByID(1117168011, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileWithDefaultApp(path) {
    return $Call.ByID(1193656674, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileAsBase64(path) {
    return $Call.ByID(2508253217, path);
}

/**
 * @param {string} src
 * @param {string} dest
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(src, dest) {
    return $Call.ByID(447518628, src, dest);
}

/**
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(cols, rows) {
    return $Call.ByID(3309742912, cols, rows);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfiles(data) {
    return $Call.ByID(2747840815, data);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(data) {
    return $Call.ByID(1632959616, data);
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function ShowMessage(title, message) {
    return $Call.ByID(368851792, title, message);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ShowOpenDialog() {
    return $Call.ByID(271827769);
}

/**
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function ShowSaveDialog(defaultName) {
    return $Call.ByID(3437106732, defaultName);
}

/**
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(localPath, remotePath) {
    return $Call.ByID(3829671223, localPath, remotePath);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(data) {
    return $Call.ByID(3608916995, data);
}
