// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application struct that holds SSH, SFTP, and terminal state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ConnectSSH initiates an SSH connection in a background goroutine.
 * @param {string} host
 * @param {string} port
 * @param {string} username
 * @param {string} password
 * @param {string} privateKeyText
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function ConnectSSH(host, port, username, password, privateKeyText, passphrase) {
    return $Call.ByID(2974803588, host, port, username, password, privateKeyText, passphrase);
}

/**
 * DeleteFile removes a remote file or directory.
 * @param {string} path
 * @param {boolean} isDir
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path, isDir) {
    return $Call.ByID(3253734293, path, isDir);
}

/**
 * DeleteLocalFile removes a file from the local filesystem.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteLocalFile(path) {
    return $Call.ByID(3211582508, path);
}

/**
 * DisconnectSSH closes the SFTP and SSH connections and emits a disconnect event.
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectSSH() {
    return $Call.ByID(1240619328);
}

/**
 * DownloadFile streams a remote file to a local path with progress events.
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(remotePath, localPath) {
    return $Call.ByID(3477154054, remotePath, localPath);
}

/**
 * DownloadToTemp downloads a remote file to a temp directory for preview.
 * @param {string} remotePath
 * @param {string} safeName
 * @returns {$CancellablePromise<string>}
 */
export function DownloadToTemp(remotePath, safeName) {
    return $Call.ByID(1152115075, remotePath, safeName);
}

/**
 * GetConfigDir returns the config directory path (~/.config/ripple-ssh), creating it if needed.
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigDir() {
    return $Call.ByID(2375802737);
}

/**
 * GetFileStats returns the size of a file in bytes.
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function GetFileStats(path) {
    return $Call.ByID(3997025289, path);
}

/**
 * GetOS returns the runtime OS name.
 * @returns {$CancellablePromise<string>}
 */
export function GetOS() {
    return $Call.ByID(2969004750);
}

/**
 * ListDirectory returns a JSON array of FileEntry for the given remote path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ListDirectory(path) {
    return $Call.ByID(3411144651, path);
}

/**
 * LoadProfiles reads the profiles JSON from the config directory.
 * Returns "[]" if no profiles exist yet.
 * @returns {$CancellablePromise<string>}
 */
export function LoadProfiles() {
    return $Call.ByID(1373793870);
}

/**
 * LoadSettings reads the settings JSON from the config directory.
 * Returns "{}" if no settings exist yet.
 * @returns {$CancellablePromise<string>}
 */
export function LoadSettings() {
    return $Call.ByID(2629865441);
}

/**
 * Mkdir creates a remote directory.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(path) {
    return $Call.ByID(1117168011, path);
}

/**
 * OpenFileWithDefaultApp opens a file with the OS default application.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileWithDefaultApp(path) {
    return $Call.ByID(1193656674, path);
}

/**
 * ReadFileAsBase64 reads a file and returns its contents as a base64 string.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileAsBase64(path) {
    return $Call.ByID(2508253217, path);
}

/**
 * RenameFile moves or renames a remote file.
 * @param {string} src
 * @param {string} dest
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(src, dest) {
    return $Call.ByID(447518628, src, dest);
}

/**
 * ResizeTerminal resizes the PTY dimensions.
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(cols, rows) {
    return $Call.ByID(3309742912, cols, rows);
}

/**
 * SaveProfiles writes the profiles JSON to the config directory.
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfiles(data) {
    return $Call.ByID(2747840815, data);
}

/**
 * SaveSettings writes the settings JSON to the config directory.
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(data) {
    return $Call.ByID(1632959616, data);
}

/**
 * ShowMessage shows a native dialog with Yes/No buttons and returns the choice.
 * Returns "No" if the dialog is dismissed or times out after 5 minutes.
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function ShowMessage(title, message) {
    return $Call.ByID(368851792, title, message);
}

/**
 * ShowOpenDialog opens a native file open dialog.
 * @returns {$CancellablePromise<string>}
 */
export function ShowOpenDialog() {
    return $Call.ByID(271827769);
}

/**
 * ShowSaveDialog opens a native save file dialog.
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function ShowSaveDialog(defaultName) {
    return $Call.ByID(3437106732, defaultName);
}

/**
 * UploadFile streams a local file to a remote path with progress events.
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(localPath, remotePath) {
    return $Call.ByID(3829671223, localPath, remotePath);
}

/**
 * WriteTerminal writes user input to the terminal's stdin.
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(data) {
    return $Call.ByID(3608916995, data);
}
