// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSSH(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteLocalFile(arg1:string):Promise<void>;

export function DisconnectSSH():Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DownloadToTemp(arg1:string,arg2:string):Promise<string>;

export function GetConfigDir():Promise<string>;

export function GetFileStats(arg1:string):Promise<number>;

export function GetOS():Promise<string>;

export function ListDirectory(arg1:string):Promise<string>;

export function LoadProfiles():Promise<string>;

export function LoadSettings():Promise<string>;

export function Mkdir(arg1:string):Promise<void>;

export function OpenFileWithDefaultApp(arg1:string):Promise<void>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SaveProfiles(arg1:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<string>;

export function ShowOpenDialog():Promise<string>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
