// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSSH(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteLocalFile(arg1) {
  return window['go']['main']['App']['DeleteLocalFile'](arg1);
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadToTemp(arg1, arg2) {
  return window['go']['main']['App']['DownloadToTemp'](arg1, arg2);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Mkdir(arg1) {
  return window['go']['main']['App']['Mkdir'](arg1);
}

export function OpenFileWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenFileWithDefaultApp'](arg1);
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SaveProfiles(arg1) {
  return window['go']['main']['App']['SaveProfiles'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShowOpenDialog() {
  return window['go']['main']['App']['ShowOpenDialog']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
